class CONFIG:
    CHECK_DATA = True
    CHECK_LRC = True
    SELFTEST_TIMEOUT_SEC = 5
    TESTCHANNEL_DEFAULT_DATALEN = 255
    TESTCHANNEL_MAX_DATALEN = 1023
    TESTCHANNEL_DEFAULT_DATABYTE = 'AA'
    BASE_SIGNAL_DESCRIPTOR_SIZE = 17